# Generated by Django 3.0.4 on 2020-03-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid_world',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recov', models.IntegerField()),
            ],
        ),
    ]
