# Generated by Django 3.0.4 on 2020-03-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid_world',
            old_name='recov',
            new_name='recovered',
        ),
        migrations.RenameField(
            model_name='covid_world',
            old_name='id',
            new_name='stat_id',
        ),
    ]
