# Generated by Django 2.2.7 on 2020-03-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200330_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='active_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_cases', models.IntegerField()),
                ('mild_cases', models.IntegerField()),
                ('critical_cases', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='closed_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.IntegerField()),
                ('discharged', models.IntegerField()),
                ('dead', models.IntegerField()),
            ],
        ),
    ]
