# Generated by Django 2.2.7 on 2020-03-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_active_cases_closed_cases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='active_cases',
        ),
        migrations.DeleteModel(
            name='closed_cases',
        ),
    ]
