# Generated by Django 2.2.7 on 2020-03-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200331_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='active_cases',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('active_cases', models.IntegerField()),
                ('mild_cases', models.IntegerField()),
                ('critical_cases', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='closed_cases',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('outcome', models.IntegerField()),
                ('discharged', models.IntegerField()),
                ('dead', models.IntegerField()),
            ],
        ),
    ]
