# Generated by Django 2.2.7 on 2020-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20200401_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='covid_country',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('total_cases', models.IntegerField()),
                ('today_cases', models.IntegerField()),
                ('total_deaths', models.IntegerField()),
                ('today_deaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('active', models.IntegerField()),
                ('critical', models.IntegerField()),
            ],
        ),
    ]
