# Generated by Django 2.2.7 on 2020-04-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_covid_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid_country',
            old_name='country',
            new_name='country_name',
        ),
    ]
