# Generated by Django 2.2.7 on 2020-04-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20200401_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covid_country',
            old_name='active',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='covid_country',
            old_name='country_name',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='covid_country',
            old_name='critical',
            new_name='Critical',
        ),
        migrations.RenameField(
            model_name='covid_country',
            old_name='recovered',
            new_name='Recovered',
        ),
        migrations.RenameField(
            model_name='covid_country',
            old_name='today_cases',
            new_name='Today_Cases',
        ),
        migrations.RenameField(
            model_name='covid_country',
            old_name='today_deaths',
            new_name='Today_Deaths',
        ),
        migrations.RenameField(
            model_name='covid_country',
            old_name='total_cases',
            new_name='Total_Cases',
        ),
        migrations.RenameField(
            model_name='covid_country',
            old_name='total_deaths',
            new_name='Total_Deaths',
        ),
    ]
