# Generated by Django 2.2.7 on 2020-05-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20200401_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid_country',
            name='Casepermillion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covid_country',
            name='Deathpermillion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covid_country',
            name='Testpermillion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covid_country',
            name='Tests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
