# Generated by Django 3.0.7 on 2020-06-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20200511_1023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='covid_country',
            new_name='CovidCountry',
        ),
        migrations.RenameModel(
            old_name='covid_world',
            new_name='CovidWorld',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Casepermillion',
            new_name='casepermillion',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Critical',
            new_name='critical',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Deathpermillion',
            new_name='deathpermillion',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Recovered',
            new_name='recovered',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Testpermillion',
            new_name='testpermillion',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Tests',
            new_name='tests',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Today_Cases',
            new_name='today_Cases',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Today_Deaths',
            new_name='today_Deaths',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Total_Cases',
            new_name='total_Cases',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='Total_Deaths',
            new_name='total_Deaths',
        ),
    ]
