# Generated by Django 3.0.7 on 2020-06-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20200630_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidcountry',
            old_name='today_Cases',
            new_name='today_cases',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='today_Deaths',
            new_name='today_deaths',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='total_Cases',
            new_name='total_cases',
        ),
        migrations.RenameField(
            model_name='covidcountry',
            old_name='total_Deaths',
            new_name='total_deaths',
        ),
    ]
