# Generated by Django 3.1.1 on 2020-09-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20200630_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covidcountry',
            options={'verbose_name_plural': 'Covid Countries'},
        ),
    ]
